apiVersion: apps/v1
kind: Deployment
metadata:
  name: bagisto-app
  namespace: bagisto
  labels:
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      name: bagisto-app
      labels:
        app: bagisto-app
        tier: backend
    spec:
      containers:
        - name: bagisto-container
          image: ""
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: 400m
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: bagisto-dinamic-configmap
            - configMapRef:
                name: bagisto-configmap
            - secretRef:
                name: bagisto-secret
                #          livenessProbe:
                #            failureThreshold: 3
                #            httpGet:
                #              path: /health
                #              port: 9000
                #              scheme: HTTP
                #            initialDelaySeconds: 3
                #            periodSeconds: 30
                #            successThreshold: 1
                #            timeoutSeconds: 5
                #          readinessProbe:
                #            failureThreshold: 3
                #            httpGet:
                #              path: /health
                #              port: 9000
                #              scheme: HTTP
                #            initialDelaySeconds: 3
                #            periodSeconds: 30
                #            successThreshold: 1
                #            timeoutSeconds: 1
  selector:
    matchLabels:
      app: bagisto-app
      tier: backend
