#Hpa
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bagisto-app-hpa
  namespace: bagisto
  labels:
    app: bagisto-app
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bagisto-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80