#Hpa
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bagisto-web-hpa
  namespace: bagisto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bagisto-web
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80